### ISSUE TITLE
Hello hello!

### ISSUE THREAD

**Issue by nickwilliams-eventbrite** [kwelch/you-pick#1]
I'm reporting an issue so that Kyle and I can test conversation locking.

**I can even edit yours**

**Comment by nickwilliams-eventbrite** [comment]
Comment comment

**Comment by nickwilliams-eventbrite** [comment]
Another comment

**Comment by nickwilliams-eventbrite** [comment]
Time to lock!

**Comment by kwelch** [comment]
I can comment still

I can also edit
